const expectedOutput = [
  {
    id: 1,
    verse: [
      "",
      "Blessed is the one who does not walk in step with the wicked or stand in the way that sinners take or sit in the company of mockers,",
      "but whose delight is in the law of the Lord, and who meditates on his law day and night.",
      "That person is like a tree planted by streams of water, which yields its fruit in season and whose leaf does not wither -- whatever they do prospers.",
      "Not so the wicked! They are like chaff that the wind blows away.",
      "Therefore the wicked will not stand in the judgement,",
      "nor sinners in the assembly of the righteous.",
      "For the LORD watches over the way of the righteous,",
      "but the way of the wicked leads to destruction",
    ],
    book: 1,
    version: "NIV",
  },
  {
    id: 2,
    verse: [
      "",
      "Why do the nations conspire and the peoples plot in vain?",
      "The kings of the Earth rise up and the rules band together against the LORD and against his anointed, saying,",
      "Let us break their chains and throw off their shackles.",
      "The One enthroned in heaven laughs; the Lord scoffs at them.",
      "He rebukes them in his anger and terrifies them in his wrath, saying,",
      `"I have installed my king on Zion, my holy mountain."`,
      "I will proclaim the Lord's decree:",
      `He said to me, "You are my son; today I have become your father.`,
      `Ask me, and I will make the nations your inheritance, the ends of the Earth your possession.`,
      `You will break them with a rod of iron; you will dash them to pieces like pottery."`,
      "Therefore, you kings, be wise; be warned, you rulers of the earth.",
      "Serve the Lord with fear and celebrate his rule with trembling.",
      "Kiss his son, or he will be angry and your way will lead to your destruction,",
      "for his wrath can flare up in a moment. Blessed are all who take refuge in him.",
    ],
    book: 1,
    version: "NIV",
  },
  {
    id: 3,
    verse: [
      "",
      "Lord, how many are my foes! How many rise up against me!",
      `Many are saying of me, "God will not deliver him."`,
      "But you, Lord, are a shield around me, my glory, the One who lifts my head high.",
      "I call out to the Lord, and he answers me from his holy mountain.",
      "I lie down and sleep; I wake again, because the Lord sustains me.",
      "I will not fear though tens of thousands assail me on every side.",
      "Arise, Lord! Deliver me, my God! Strike all my enemies on the jaw; break the teeth of the wicked.",
      "From the Lord comes deliverance. May your blessing be on your people.",
    ],
    book: 1,
    version: "NIV",
  },
];

module.exports = expectedOutput;
